### ISSUE TITLE
Sleeping bag

### ISSUE THREAD

**Issue by LJack2k** [Icohedron/SleepVote#1]
I'm on the FTB Beyond modpack. I disabled morpheus mod and installed this one. But now when people use the sleeping bag they get disconnected with an exception error. I have don't a log file sadly. But it always disconnects people without exception.

**Comment by Icohedron** [comment]
Without the logs, I can not easily determine the root cause of the issue. Any pointer to it, such as the exception message displayed on the players' clients or in the server console will be of much help.
This plugin was also made for SpongeVanilla, and has not yet been tested on SpongeForge, so there may be a few compatibility issues.

For now, though, you should keep using Morpheus.
I'll see what I can do to fix the issue.

**Comment by LJack2k** [comment]
Ok I managed to get the following from the server log when it happens. Hopefully this will help you.

https://pastebin.com/nDWkgvdL

**Comment by Icohedron** [comment]
At a glance, it doesn't seem to be a plugin-related problem, but more like a mod problem.
Nonetheless, I'll investigate further. Thanks!

**Comment by LJack2k** [comment]
Good news. In FTB Beyond 1.6.1 this bug doesnt happen anymore.
