### ISSUE TITLE
Unable to download latest version off Ore

### ISSUE THREAD

**Issue by YOYOK9** [Icohedron/SleepVote#5]
I keep getting this error whenever I try to download the latest update:

"Ore is experiencing difficulties.
Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Icohedron/Sleep Vote/sleepvote-0.4.2.jar]"

**Comment by LJack2k** [comment]
You can also get it on github. Check the releases on here.

Op 5 mei 2017 18:43 schreef "YOYOK9" <notifications@github.com>:

**Comment by Icohedron** [comment]
May be an issue with my PGP keys since migrating over to a Linux development environment.

For now, download it from the releases page on GitHub or build it from source.

**Comment by Icohedron** [comment]
I created a whole new PGP key following the guideline that "Ore requires each plugin file (ZIP or JAR) to be uploaded with a detached Pretty Good Privacy (PGP) signature for a public key that is associated with the email that you signed up to Sponge with." I noticed that I had made my PGP key with my alias' email rather than the one I signed up with. So I changed my account's public key a few days ago and just uploaded a new version of the plugin.
But the download is still broken...
