### ISSUE TITLE
Sleeping doesn't trigger SleepVote

### ISSUE THREAD

**Issue by SamuelWAnderson45** [Icohedron/SleepVote#6]
I have installed SleepVote on a Forge 1.10.2-12.18.3.2316 server with SpongeForge. I'm using this as a replacement for Morpheus due to its incompatibility with Sponge. Unfortunately, while all the /sleepvote commands appear to work fine, the "{Player} is sleeping" message is never triggered and the time is never set to day. There is no error in the server log.

Sorry there are no logs; if there was anything to see I'd give it to you.

It shouldn't matter, but this server is behind a BungeeCord (Waterfall technically) proxy if you're familiar with that.

**Comment by Icohedron** [comment]
Players with the permission 'sleepvote.hidden' are skipped by the plugin. Make sure you're sleeping without op to see if that fixes your issue.
If you're using a permissions plugin, you can use either '/sleepvote hide' to toggle the permission on/off for your player or unset the permission manually for your group or user -- in LuckPerms, it would be '/lp user <Username> permission unset sleepvote.hidden' or '/lp group <Group Name> permission unset sleepvote.hidden'
You may have to give the '/sleepvote hide' command a couple moments in order for it to communicate with the permissions plugin and toggle the permission accordingly. For servers without a permissions plugin, the command should still work but it won't persist on relogs and restarts, and sometimes it doesn't work at all even when it says it does.

I may end up changing how the hiding system works since quite a few people have been confused with this same issue.

**Comment by SamuelWAnderson45** [comment]
So being /op hides you by default?

Just saw your FAQ, sorry I missed that earlier.

**Comment by Icohedron** [comment]
It's changing in the next update. Stay tuned.

**Comment by SamuelWAnderson45** [comment]
Thanks!

**Comment by Icohedron** [comment]
Players with the permission 'sleepvote.hidden' are no longer ignored by default as of 0.6-BETA-1.
You can re-enable it via the configuration file's "ignore_admins" field.

**Comment by ThomMassey** [comment]
Im on the last version and it only lets me sleep once, then I cant sleep again, I have to reload everytime and I cant be on 24/7 reloading for my players
